export default [
  'Major Depressive Disorder',
  'Bipolar I Disorder',
  'Bipolar II Disorder',
  'Schizophrenia',
  'Schizoaffective Disorder',
  'Generalized Anxiety Disorder',
  'Panic Disorder',
  'Social Anxiety Disorder',
  'Obsessive-Compulsive Disorder (OCD)',
  'Post-Traumatic Stress Disorder (PTSD)',
  'Borderline Personality Disorder',
  'Eating Disorders',
  'Dissociative Identity Disorder (DID)',
  'Attention-Deficit/Hyperactivity Disorder (ADHD)',
  'Autism Spectrum Disorder',
  'Alcohol Use Disorder',
  'Substance Use Disorders',
  'Antisocial Personality Disorder',
  'Narcissistic Personality Disorder',
  'Histrionic Personality Disorder',
  'Avoidant Personality Disorder',
  'Schizoid Personality Disorder',
  'Paranoid Personality Disorder',
  'Dependent Personality Disorder',
  'OCD-Related Disorders',
  'Body Dysmorphic Disorder',
  'Hoarding Disorder',
  'Trichotillomania (Hair-Pulling Disorder)',
  'Excoriation (Skin-Picking) Disorder',
  'Panic Disorder with Agoraphobia',
  'Specific Phobia',
  'Agoraphobia',
  'Generalized Anxiety Disorder',
  'Selective Mutism',
  'Separation Anxiety Disorder',
  'Premenstrual Dysphoric Disorder (PMDD)',
  'Bereavement',
  'Cyclothymic Disorder',
  'Schizophreniform Disorder',
  'Brief Psychotic Disorder',
  'Schizophrenia Spectrum and Other Psychotic Disorders',
  'Schizophrenia Due to Another Medical Condition',
  'Substance/Medication-Induced Psychotic Disorder',
  'Psychotic Disorder Due to Another Medical Condition',
  'Catatonia',
  'Neurocognitive Disorder',
  'Frontotemporal Neurocognitive Disorder',
  'Anorexia Nervosa',
  'Bulimia Nervosa',
  'Binge-Eating Disorder',
  'Avoidant/Restrictive Food Intake Disorder (ARFID)',
  'Rumination Disorder',
  'Pica',
]
