export const thought_contents = [
  'delusion',
  'over valued idea',
  'phobia',
  'obsession',
  'preoccupation',
]

export const thought_forms = [
  'normal',
  'circumstantial',
  'tangential',
  'loose associations',
  'derailment',
  'word salad',
]

export const perceptions = [
  'auditory', 'visual', 'hallucinations', 'illusion', 'pseudohallucination',
]

export const managements = [
  'fluoxetine',
  'moclobemide',
  'haloperidol',
  'sertraline',
  'venlafaxine',
  'diazepam',
  'lorazepam',
  'paroxetine',
  'amitriptyline',
  'quetiapine',
  'risperidone',
  'clonazepam',
  'alprazolam',
  'citalopram',
  'escitalopram',
  'bupropion',
  'olanzapine',
  'clozapine',
  'lithium',
  'carbamazepine',
  'valproic acid',
  'trazodone',
  'aripiprazole',
  'ziprasidone',
  'lurasidone',
  'lithium carbonate',
  'lamotrigine',
  'topiramate',
  'buspirone',
  'phenelzine',
  'selegiline',
  'venlafaxine',
  'duloxetine',
  'mirtazapine',
  'tranylcypromine',
  'propranolol',
  'temazepam',
  'zolpidem',
  'zaleplon',
  'doxepin',
  'hydroxyzine',
  'chlorpromazine',
  'trifluoperazine',
  'fluphenazine',
  'aripiprazole',
  'asenapine',
  'brexpiprazole',
  'cariprazine',
  'chlorpromazine',
  'clozapine',
  'fluphenazine',
  'haloperidol',
  'iloperidone',
  'lurasidone',
  'molindone',
  'olanzapine',
  'paliperidone',
  'perphenazine',
  'pimavanserin',
  'quetiapine',
  'risperidone',
  'thioridazine',
  'trifluoperazine',
  'ziprasidone',
]

export const diagnoses = [
  'Major Depressive Disorder',
  'Bipolar I Disorder',
  'Bipolar II Disorder',
  'Schizophrenia',
  'Schizoaffective Disorder',
  'Generalized Anxiety Disorder',
  'Panic Disorder',
  'Social Anxiety Disorder',
  'Obsessive-Compulsive Disorder (OCD)',
  'Post-Traumatic Stress Disorder (PTSD)',
  'Borderline Personality Disorder',
  'Eating Disorders',
  'Dissociative Identity Disorder (DID)',
  'Attention-Deficit/Hyperactivity Disorder (ADHD)',
  'Autism Spectrum Disorder',
  'Alcohol Use Disorder',
  'Substance Use Disorders',
  'Antisocial Personality Disorder',
  'Narcissistic Personality Disorder',
  'Histrionic Personality Disorder',
  'Avoidant Personality Disorder',
  'Schizoid Personality Disorder',
  'Paranoid Personality Disorder',
  'Dependent Personality Disorder',
  'OCD-Related Disorders',
  'Body Dysmorphic Disorder',
  'Hoarding Disorder',
  'Trichotillomania (Hair-Pulling Disorder)',
  'Excoriation (Skin-Picking) Disorder',
  'Panic Disorder with Agoraphobia',
  'Specific Phobia',
  'Agoraphobia',
  'Generalized Anxiety Disorder',
  'Selective Mutism',
  'Separation Anxiety Disorder',
  'Premenstrual Dysphoric Disorder (PMDD)',
  'Bereavement',
  'Cyclothymic Disorder',
  'Schizophreniform Disorder',
  'Brief Psychotic Disorder',
  'Schizophrenia Spectrum and Other Psychotic Disorders',
  'Schizophrenia Due to Another Medical Condition',
  'Substance/Medication-Induced Psychotic Disorder',
  'Psychotic Disorder Due to Another Medical Condition',
  'Catatonia',
  'Neurocognitive Disorder',
  'Frontotemporal Neurocognitive Disorder',
  'Anorexia Nervosa',
  'Bulimia Nervosa',
  'Binge-Eating Disorder',
  'Avoidant/Restrictive Food Intake Disorder (ARFID)',
  'Rumination Disorder',
  'Pica',
]

export const cognitive = [
  'Oriented',
  'disoriented',
  'Attentive',
  'poor attention',
  'poor short memory',
  'poor intermediate memory',
  'poor long memory',
  'low IQ',
  'concrete thinking',
  'poor judgement',
]

export const speeches = [
  'slow rate',
  'regular rate',
  'fast rate',
  'pressured speech',
  'hesitant',
  'low volume',
  'high volume',
  'poor quantity',
  'overabundance',
  'fluent',
  'aphasia',
  'dysarthria',
  'stuttering',
  'tone',
  'short latency',
  'long latency',
]

export const moods = [
  'dysthymic',
  'euphoric',
  'euthymic',
  'intense range',
  'full range',
  'restricted affect',
  'blunted affect',
  'flat affect',
]

export const behaviors = [
  'aroused',
  'good eye contact',
  'poor eye contact',
  'disinhibited',
  'good attitude',
  'poor attitude',
  'abnormal movement',
]

export const appearances = [
  'abnormal gait',
  'abnormal posture',
  'inappropriate clothes',
  'poor self-care',
  'poor health',
]

export const substances = [
  'Alcohol',
  'Tobacco',
  'Cannabis (Marijuana)',
  'Prescription Painkillers (Opioids)',
  'Heroin',
  'Cocaine',
  'Methamphetamine',
  'Ecstasy (MDMA)',
  'LSD (Acid)',
  'Psilocybin (Magic Mushrooms)',
  'Ketamine',
  'Inhalants',
  'Synthetic Cannabinoids (Spice/K2)',
  'Benzodiazepines',
  'Synthetic Cathinones (Bath Salts)',
  'Anabolic Steroids',
  'DXM (Dextromethorphan)',
  'GHB (Gamma-Hydroxybutyrate)',
  'Kratom',
  'Salvia Divinorum',
]

export const suicides = [
  'ideation',
  'attempt',
  'plan',
  'self harm',
  'self mutilation',
]

export const chronic_disorders = [
  'Diabetes',
  'Hypertension (High Blood Pressure)',
  'Asthma',
  'Chronic Obstructive Pulmonary Disease (COPD)',
  'Arthritis',
  'Coronary Artery Disease (CAD)',
  'Chronic Kidney Disease (CKD)',
  'Heart Failure',
  'Stroke',
  'Obesity',
  'Alzheimer\'s Disease',
  'Depression',
  'Anxiety Disorders',
  'Chronic Migraines',
  'Irritable Bowel Syndrome (IBS)',
  'Epilepsy',
  'Chronic Pain Syndromes',
  'Autoimmune Diseases (e.g., Rheumatoid Arthritis, Lupus)',
  'Crohn\'s Disease',
  'Ulcerative Colitis',
]

export const insights = [
  'poor insight',
  'good insight',
]

export const genders = [
  'male', 'female',
]

export const residences = [
  'Baghdad',
  'Najaf',
  'Babil',
  'Karbala',
  'Anbar',
  'Basra',
  'Dhi Qar',
  'Diyala',
  'Qadisiyyah',
  'Duhok',
  'Erbil',
  'Kirkuk',
  'Maysan',
  'Muthanna',
  'Ninawa',
  'Salah Al-Din',
  'Sulaymaniyah',
  'Wasit',
]

export const educations = [
  'illiterate',
  'primary school',
  'secondary school',
  'college',
  'higher education',
]

export const marital_statuses = [
  'single',
  'married',
  'divorced',
  'widowed',
]

export const childrens = [
  '1', '2', '3', '4', '5', '6', '7', '8',
]

export const occupations = [
  'free worker',
]
